### ISSUE TITLE
Wrong header names in Object Operations

### ISSUE THREAD

**Issue by rlk833** [IBM-Bluemix-Docs/cloud-object-storage#12]
IN 

https://console.bluemix.net/docs/services/cloud-object-storage/api-reference/api-reference-objects.html#object-operations

The headers for the operations such as DownLoad that are of the form 'x-amz-copy-source-if-...' are wrong. I spent over two hours trying to get this to work correctly when I realized the headers are the actual official HTTP type headers. Such as where 'x-amz-copy-source-if-match' was shown as the header to use it is really the header 'If-Match'. Same for x-amz-...-if-none-matched, it was simply 'If-None-Match'

One more minor documentation problem: 

In 

https://console.bluemix.net/docs/services/cloud-object-storage/api-reference/common-headers-errors.html#common-headers-error-codes

You are missing the status code 304 - which is Not Modified. That is the code that is returned on a Download operation with the header If-None-Match and the ETag matches. Again this is standard official HTTP.

Thanks.
Rich Kulp (I'm in IBM)

**Comment by nglange** [comment]
Thanks Rich, I've altered the object reference docs.  The "Copy object" headers were mistakenly used for both HEAD and GET object.  While standard `if-match` style headers do work, we consider them experimental because of potential race conditions within the system.  As soon as we're confident that there's no potential for conflict, it will be documented properly.

`304`, `200`, `201`, etc aren't listed because they're standard HTTP.
